let nameInput = document.querySelector('#exampleInputName')
let genderInput = document.querySelectorAll('#form-user-create [name=gender]:checked')
let birthInput = document.querySelector('#exampleInputBirth')
let countryInput = document.querySelector('#exampleInputCountry')
let emailInput = document.querySelector('#exampleInputEmail')
let passwordInput = document.querySelector('#exampleInputPassword')
let photoInput = document.querySelector('#exampleInputFile')
let adminInput = document.querySelector('#exampleInputAdmin')